version: '3'
services:
    datastore:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=1234
        volumes:
            - /var/lib/postgresql
            - ./sportsdb:/docker-entrypoint-initdb.d

    datastore_admin:
        image: dpage/pgadmin4
        ports:
            - "5433:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.fr
            - PGADMIN_DEFAULT_PASSWORD=1234
        volumes:
            - /var/lib/pgadmin
