name: CI

on: [push, pull_request]

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: build experimentation architecture with docker-compose
              run: docker-compose up -d

            - name: check running containers
              run: docker ps

            - name: wait the datastore with sportsdb is up and ready to be used
              run: docker-compose run ci_tests pipenv run wait_datastore

            - name: show docker-compose logs
              run: docker-compose logs --tail 100

            - name: validate the implementation of sportsdb_backend_python
              run: docker-compose run ci_tests pipenv run python ci_tests/test_sportsdb_backend_python.py

            - name: validate the implementation of sportsdb_backend_typescript
              run: docker-compose run ci_tests pipenv run python ci_tests/test_sportsdb_backend_typescript.py
